cp -r ./fcitx5 ~/.config/
cp -r ./fcitx ~/.config/
cp -r ./hypr ~/.config/
cp -r ./alacritty ~/.config/
cp -r ./waybar ~/.config/
cp -r ./fastfetch ~/.config/
cp -r ./fish ~/.config/
cp -r ./fish ~/.config/
cp -r ./wallpaper ~/图片/